/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.art.iai.ui;

import br.art.iai.bean.Usuario;
import br.art.iai.model.UsuarioModel;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Paulo
 */
public class DialogoNovoUsuario extends javax.swing.JDialog {

    private boolean isUpdate;
    private Usuario usuario;

    public DialogoNovoUsuario(java.awt.Frame parent, boolean modal,
            boolean isUpdate, Usuario usuario) {
        super(parent, modal);
        initComponents();

        this.isUpdate = isUpdate;
        this.usuario = usuario;

        if (isUpdate == false) {
            //incluir novo registro
            if (usuario != null) {
                email.setText(usuario.email);
                senha.setText(usuario.senha);
            }

            botaoExcluir.setEnabled(false);
        } else {
            //atualizar um registro
            email.setText(usuario.email);
            senha.setText(usuario.senha);
            nome.setText(usuario.nome);

            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            dataNascimento.setText(sdf.format(usuario.dataNascimento));
            botaoExcluir.setEnabled(true);
            email.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        labelNome = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        labelSenha = new javax.swing.JLabel();
        senha = new javax.swing.JPasswordField();
        labelDataNascimento = new javax.swing.JLabel();
        dataNascimento = new javax.swing.JTextField();
        botaoSalvar = new javax.swing.JButton();
        botaoExcluir = new javax.swing.JButton();
        botaoLimparCampos = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelEmail.setText("E-mail:");

        labelNome.setText("Nome:");

        labelSenha.setText("Senha:");

        labelDataNascimento.setText("Data de Nascimento:");

        botaoSalvar.setText("Salvar");
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        botaoExcluir.setText("Excluir");
        botaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirActionPerformed(evt);
            }
        });

        botaoLimparCampos.setText("Limpar Campos");
        botaoLimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparCamposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelSenha)
                    .addComponent(senha, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDataNascimento)
                    .addComponent(dataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(labelEmail, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(email, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                        .addComponent(labelNome, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nome, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(botaoExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(botaoLimparCampos)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelDataNascimento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoSalvar)
                    .addComponent(botaoExcluir)
                    .addComponent(botaoLimparCampos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoLimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparCamposActionPerformed
        // TODO add your handling code here:
        if (!isUpdate) {
            email.setText("");
        }
        senha.setText("");
        nome.setText("");
        dataNascimento.setText("");
    }//GEN-LAST:event_botaoLimparCamposActionPerformed

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        // TODO add your handling code here:
        if (this.isUpdate == false) {
            //inclusao
            //usuario.dataNascimento = dataNascimento.getText();
            if (usuario == null) {
                usuario = new Usuario();
            }

            if (email.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Digite o email");
            } else if (senha.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Digite a senha");
            } else if (nome.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Digite o nome");
            } else {
                usuario.email = email.getText();
                usuario.senha = senha.getText();
                usuario.nome = nome.getText();

                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                try {
                    usuario.dataNascimento = sdf.parse(dataNascimento.getText());

                    if (UsuarioModel.Incluir(this.usuario) == true) {
                        //conseguiu inserir
                        JOptionPane.showMessageDialog(this, "Usuário incluído com sucesso!!");
                        dispose();
                    } else {
                        //deu erro no include
                        JOptionPane.showMessageDialog(this, "Erro ao incluir usuário");
                    }
                } catch (ParseException ex) {
                    JOptionPane.showMessageDialog(this, "Digite a data com dd/mm/yyyy");
                }
            }

        } else {
            //alteracao
            //
            usuario.nome = nome.getText();
            usuario.senha = senha.getText();

            if (UsuarioModel.Atualizar(usuario)) {
                JOptionPane.showMessageDialog(this, "Dados alterados com sucesso");
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao atualizar registro");
            }
        }
    }//GEN-LAST:event_botaoSalvarActionPerformed

    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirActionPerformed
        // TODO add your handling code here:
        if (UsuarioModel.Excluir(usuario.email)) {
            JOptionPane.showMessageDialog(this, "Excluído com sucesso!");
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Não foi possível excluir");
        }
    }//GEN-LAST:event_botaoExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JButton botaoLimparCampos;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JTextField dataNascimento;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelDataNascimento;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JTextField nome;
    private javax.swing.JPasswordField senha;
    // End of variables declaration//GEN-END:variables
}
