/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.art.iai.ui;

/**
 *
 * @author Paulo
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraMenu = new javax.swing.JMenuBar();
        itemCadastro = new javax.swing.JMenu();
        itemCadastroNovoUsuario = new javax.swing.JMenuItem();
        itemCadastroListaUsuarios = new javax.swing.JMenuItem();
        itemSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        itemCadastro.setText("Cadastro");

        itemCadastroNovoUsuario.setText("Novo Usuário");
        itemCadastroNovoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCadastroNovoUsuarioActionPerformed(evt);
            }
        });
        itemCadastro.add(itemCadastroNovoUsuario);

        itemCadastroListaUsuarios.setText("Lista de Usuários");
        itemCadastroListaUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCadastroListaUsuariosActionPerformed(evt);
            }
        });
        itemCadastro.add(itemCadastroListaUsuarios);

        barraMenu.add(itemCadastro);

        itemSair.setText("Sair");
        itemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSairActionPerformed(evt);
            }
        });
        barraMenu.add(itemSair);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSairActionPerformed
        // TODO add your handling code here:Sys
        System.exit(0);
    }//GEN-LAST:event_itemSairActionPerformed

    private void itemCadastroNovoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCadastroNovoUsuarioActionPerformed
        // TODO add your handling code here:
        DialogoNovoUsuario novo = new DialogoNovoUsuario(this, true, false, null);
        novo.setVisible(true);
    }//GEN-LAST:event_itemCadastroNovoUsuarioActionPerformed

    private void itemCadastroListaUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCadastroListaUsuariosActionPerformed
        // TODO add your handling code here:
        DialogoListaUsuarios lista = new DialogoListaUsuarios(this, true);
        lista.setVisible(true);
    }//GEN-LAST:event_itemCadastroListaUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new TelaPrincipal().setVisible(true);
                TelaPrincipal principal = new TelaPrincipal();
                principal.setVisible(true);
                DialogoLogin login = new DialogoLogin(principal, true);
                login.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenu itemCadastro;
    private javax.swing.JMenuItem itemCadastroListaUsuarios;
    private javax.swing.JMenuItem itemCadastroNovoUsuario;
    private javax.swing.JMenu itemSair;
    // End of variables declaration//GEN-END:variables
}
